### ISSUE TITLE
West Europa cannot find Image

### ISSUE THREAD

**Issue by abij** [cloudera/director-azure-plugin#1]
Running the Cloudera Director 2.11 with Azure-plugin 1.0.1 we get an error that the Image could not be found. We are running it in West Europe

> * IMAGE 'PUBLISHER: 'cloudera', OFFER: 'cloudera-centos-6', SKU: 'CLOUDERA-CENTOS-6', VERSION: 'latest'' does not exist in Azure. Please verify the input.

This is configured at the resource:
`unzip -q -c /var/lib/cloudera-director-plugins/azure-provider-1.0.1/azure-provider-1.0.1.jar com/cloudera/director/azure/images.conf`

These are the available images:
```
az vm image list --publisher cloudera --all
Sku                Publisher    Urn                                                 Version    Offer
-----------------  -----------  --------------------------------------------------  ---------  ------------------
cloudera-centos-6  cloudera     cloudera:cloudera-centos-6:cloudera-centos-6:1.0.0  1.0.0      cloudera-centos-6
cloudera-centos-6  cloudera     cloudera:cloudera-centos-6:cloudera-centos-6:8.0.1  8.0.1      cloudera-centos-6
6_7                cloudera     cloudera:cloudera-centos-os:6_7:1.0.0               1.0.0      cloudera-centos-os
7_2                cloudera     cloudera:cloudera-centos-os:7_2:1.0.2               1.0.2      cloudera-centos-os
````

Quick solution is to create an images.conf as described in the [Cloudera Azure documentation](https://www.cloudera.com/documentation/director/latest/topics/director_get_started_azure_advanced_configs.html)

**Comment by mdzz** [comment]
Hi @abij 

Regarding the error you saw:
>IMAGE 'PUBLISHER: 'cloudera', OFFER: 'cloudera-centos-6', SKU: 'CLOUDERA-CENTOS-6', VERSION: 'latest'' does not exist in Azure. Please verify the input.

Please ensure the Azure service principal is a "Contributor" of your subscription (see [documentation](http://www.cloudera.com/documentation/director/latest/topics/director_get_started_azure_obtain_credentials.html#concept_jrx_gfp_hw) here).

Were you able to access the image by creating a `image.conf` file instead?

**Comment by abij** [comment]
He @mdzz, good point. We added the Director principal with the role is a Contributor.
The list I created is made with co-admin rights.
Will version latest automatically get the highest number?

I will test with custom image.conf tomorrow and let you know.

**Comment by mdzz** [comment]
>I will test with custom image.conf tomorrow and let you know.

I don't think having a custom `image.conf` file will help in this case. I thought you were able to fix the problem by having the custom `image.conf` file and was curious about how that would work (it shouldn't).

**Comment by abij** [comment]
So placing a custom image**s**.conf in /var/lib/cloudera-director-plugins/azure-provider-1.0.1/etc will override the default. The mechanism works, which is nice!

Still I get an error that the image cannot be found, so its another issue I have to debug. Probably rights or enable programmatically allow that vmImage from the Azure-Store. I'll let you know. 

New error from Cloudera Director:
`* IMAGE 'PUBLISHER: 'cloudera', OFFER: 'cloudera-centos-6', SKU: 'cloudera-centos-6', VERSION: '8.0.1'' does not exist in Azure. Please verify the input.`

**Comment by abij** [comment]
From the Azure Marketplace I can create a Cloudera-Centos-67. The template contains the following. This the same as the images.conf packaged in cloudera-director so I'll close this issue. (and debug further)

```
"imageReference": {
                        "publisher": "cloudera",
                        "offer": "cloudera-centos-6",
                        "sku": "cloudera-centos-6",
                        "version": "latest"
                    }
```

**Comment by abij** [comment]
He @mdzz, it turns out someone has screwed up the rights. The user was NOT a Contributor (anymore). It's fixed. Thx for your time.

**Comment by mdzz** [comment]
@abij No worries, glad to help :)
